server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/music_game_users
    username: postgres
    password: 9991509
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: musicGameSecretKey123456789012345678901234567890AB
  expiration: 86400000  # 24 saat (milisaniye)
  refresh-expiration: 604800000  # 7 gün (milisaniye)
